nome = str(input('Digite seu nome completo: ')).strip()
fistName = nome.split()
print('Analisando seu nome...')
print(f'Seu nome em maiúsculas é {nome.upper()}')
print(f'Seu nome em minúsculo é {nome.lower()}')
print(f'Seu nome tem ao todo {len(nome.replace(' ', ''))} letras')
# or print(f'Seu nome tem ao todo {len(nome) - nome.count(' ')} letras')
print(f'Seu primeiro nome é {fistName[0]} e tem {len(fistName[0])} letras')
# or print(f'Seu primeiro nome tem {nome.find(' ')}')

